version: '3'

services:
  front:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./web/src/:/app/src

  back:
    build:
      context: server/
      dockerfile: Dockerfile
    command: npm run serve
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/app/src
    environment:
      - BASE_URL=area.famille4.com
