version: '3'

services:
  front:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./web:/app

  back:
    build:
      context: server/
      dockerfile: Dockerfile
    command: npm run serve
    ports:
      - 3000:3000
    volumes:
        - ./server:/app
    environment:
      - BASE_URL: area.famille4.com
