version: '3'

services:
  front:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./web:/app
      - /app/node_modules

  back:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
