version: '3'

services:
  # front:
  #   build:
  #     context: web/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - ./web/src/:/app/src
  #     - builds:/builds
  #   depends_on:
  #     - mobile
  #     - back

  back:
    build:
      context: server/
      dockerfile: Dockerfile
    command: sh deploy.sh
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/app/src
    environment:
      - BASE_URL=area.cap.famille4.com
      - HOST=https://captain.cap.famille4.com
      - HOST_PASSWORD=M8a3Wty#Lgj6

  # mobile:
  #   build:
  #     context: mobile/
  #     dockerfile: Dockerfile
  #   command: 'mv /build.apk /builds/build.apk'
  #   volumes:
  #     - builds:/builds

volumes:
  builds:
    driver: local
